# Generated by Django 4.2 on 2023-06-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
