# Generated by Django 4.2 on 2023-06-27 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movimientos', '0003_movimientos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='categoria',
            field=models.CharField(help_text='Ponga cualquier categoria', max_length=100),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='La fecha actual, fecha de creacion del movimiento.', null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='monto',
            field=models.IntegerField(help_text='El monto debe ser un entero positivo.'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='nombre_movimiento',
            field=models.CharField(help_text='Nombre del movimiento, maximo 100 caracteres.', max_length=100),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], default='ingreso', help_text='Tipo de movimiento.', max_length=10),
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text='Ponga cualquier categoria que se quiera filtrar', max_length=100)),
                ('fecha_inicial', models.DateTimeField(default=django.utils.timezone.now, help_text='La fecha inicial desde la cual se quiere filtrar')),
                ('fecha_final', models.DateTimeField(default=django.utils.timezone.now, help_text='La fecha final desde la cual se quiere filtrar')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], default='ingreso', help_text='Tipo de movimiento.', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
